interface WorkerEvent {
    action: string;
    workTreeId?: string;
    correlationId?: string;
    workTree?: {
        id?: string;
    };
    plan?: {
        tasks?: PlanTaskLike[];
        risks?: unknown[];
    };
    task?: TaskRef;
    executionResults?: TaskOutcome[];
    verification?: VerificationOutcome;
}
interface PlanTaskLike {
    id?: string;
    title?: string;
    description?: string;
    agentType?: string;
    priority?: string;
    dependencies?: string[];
    estimatedDurationMinutes?: number;
}
/** Compact shape the Map iterates over. Full task rows are re-read from MariaDB. */
interface TaskRef {
    id: string;
    agentId: string | null;
    title: string;
    agentType: string;
    priority: string;
}
interface TaskOutcome {
    taskId: string;
    status: "completed" | "failed";
    artifactId?: string;
    chars?: number;
    inputTokens?: number;
    outputTokens?: number;
    error?: string;
}
interface VerificationOutcome {
    approved: boolean;
    requiresApproval: boolean;
    checks: Array<{
        name: string;
        passed: boolean;
        detail: string;
    }>;
    approvalDeadline?: string;
    approvalId?: string;
}
export declare function handler(event: WorkerEvent): Promise<TaskRef[] | {
    id: string;
    name: string;
    objective: string;
    status: string;
    progress: number;
    context: string;
    correlationId: string | undefined;
    existingTaskCount: number;
    planSummary: string | null;
    taskId?: undefined;
    artifactId?: undefined;
    chars?: undefined;
    inputTokens?: undefined;
    outputTokens?: undefined;
    workTreeId?: undefined;
    total?: undefined;
    completed?: undefined;
    failed?: undefined;
    resultCount?: undefined;
    approved?: undefined;
    reason?: undefined;
    approvalId?: undefined;
    outcome?: undefined;
    artifactCount?: undefined;
} | {
    taskId: string;
    status: "completed";
    artifactId: string;
    chars: number;
    inputTokens: number;
    outputTokens: number;
    id?: undefined;
    name?: undefined;
    objective?: undefined;
    progress?: undefined;
    context?: undefined;
    correlationId?: undefined;
    existingTaskCount?: undefined;
    planSummary?: undefined;
    workTreeId?: undefined;
    total?: undefined;
    completed?: undefined;
    failed?: undefined;
    resultCount?: undefined;
    approved?: undefined;
    reason?: undefined;
    approvalId?: undefined;
    outcome?: undefined;
    artifactCount?: undefined;
} | {
    workTreeId: string;
    total: number;
    completed: number;
    failed: number;
    progress: number;
    resultCount: number;
    correlationId: string | null;
    id?: undefined;
    name?: undefined;
    objective?: undefined;
    status?: undefined;
    context?: undefined;
    existingTaskCount?: undefined;
    planSummary?: undefined;
    taskId?: undefined;
    artifactId?: undefined;
    chars?: undefined;
    inputTokens?: undefined;
    outputTokens?: undefined;
    approved?: undefined;
    reason?: undefined;
    approvalId?: undefined;
    outcome?: undefined;
    artifactCount?: undefined;
} | {
    approved: boolean;
    reason: string;
    id?: undefined;
    name?: undefined;
    objective?: undefined;
    status?: undefined;
    progress?: undefined;
    context?: undefined;
    correlationId?: undefined;
    existingTaskCount?: undefined;
    planSummary?: undefined;
    taskId?: undefined;
    artifactId?: undefined;
    chars?: undefined;
    inputTokens?: undefined;
    outputTokens?: undefined;
    workTreeId?: undefined;
    total?: undefined;
    completed?: undefined;
    failed?: undefined;
    resultCount?: undefined;
    approvalId?: undefined;
    outcome?: undefined;
    artifactCount?: undefined;
} | {
    approved: boolean;
    reason: string;
    approvalId: string;
    id?: undefined;
    name?: undefined;
    objective?: undefined;
    status?: undefined;
    progress?: undefined;
    context?: undefined;
    correlationId?: undefined;
    existingTaskCount?: undefined;
    planSummary?: undefined;
    taskId?: undefined;
    artifactId?: undefined;
    chars?: undefined;
    inputTokens?: undefined;
    outputTokens?: undefined;
    workTreeId?: undefined;
    total?: undefined;
    completed?: undefined;
    failed?: undefined;
    resultCount?: undefined;
    outcome?: undefined;
    artifactCount?: undefined;
} | {
    outcome: string;
    workTreeId: string;
    artifactCount: number;
    id?: undefined;
    name?: undefined;
    objective?: undefined;
    status?: undefined;
    progress?: undefined;
    context?: undefined;
    correlationId?: undefined;
    existingTaskCount?: undefined;
    planSummary?: undefined;
    taskId?: undefined;
    artifactId?: undefined;
    chars?: undefined;
    inputTokens?: undefined;
    outputTokens?: undefined;
    total?: undefined;
    completed?: undefined;
    failed?: undefined;
    resultCount?: undefined;
    approved?: undefined;
    reason?: undefined;
    approvalId?: undefined;
} | {
    outcome: string;
    workTreeId: string | undefined;
    id?: undefined;
    name?: undefined;
    objective?: undefined;
    status?: undefined;
    progress?: undefined;
    context?: undefined;
    correlationId?: undefined;
    existingTaskCount?: undefined;
    planSummary?: undefined;
    taskId?: undefined;
    artifactId?: undefined;
    chars?: undefined;
    inputTokens?: undefined;
    outputTokens?: undefined;
    total?: undefined;
    completed?: undefined;
    failed?: undefined;
    resultCount?: undefined;
    approved?: undefined;
    reason?: undefined;
    approvalId?: undefined;
    artifactCount?: undefined;
}>;
export {};
